# Generated by Django 5.0.6 on 2024-06-08 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('elo_rating', models.IntegerField(verbose_name='elo rating')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('games_played', models.IntegerField(default=0, verbose_name='games played')),
                ('wins', models.IntegerField(default=0, verbose_name='wins')),
                ('losses', models.IntegerField(default=0, verbose_name='losses')),
                ('draws', models.IntegerField(default=0, verbose_name='draws')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=4)),
                ('opening', models.CharField(choices=[('Sicilian Defense', 'Sicilian Defense'), ('Ruy Lopez', 'Ruy Lopez')], max_length=50)),
                ('number_of_moves', models.IntegerField()),
                ('date_played', models.DateField()),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_games', to='core.playermodel')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_games', to='core.playermodel')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
    ]
